// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SdkPhoneLoginWithBody request with any body
	SdkPhoneLoginWithBody(ctx context.Context, params *SdkPhoneLoginParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SdkPhoneLogin(ctx context.Context, params *SdkPhoneLoginParams, body SdkPhoneLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SdkPhoneSendCodeWithBody request with any body
	SdkPhoneSendCodeWithBody(ctx context.Context, params *SdkPhoneSendCodeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SdkPhoneSendCode(ctx context.Context, params *SdkPhoneSendCodeParams, body SdkPhoneSendCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SdkMerchantVerifyTokenWithBody request with any body
	SdkMerchantVerifyTokenWithBody(ctx context.Context, params *SdkMerchantVerifyTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SdkMerchantVerifyToken(ctx context.Context, params *SdkMerchantVerifyTokenParams, body SdkMerchantVerifyTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SdkPhoneLoginWithBody(ctx context.Context, params *SdkPhoneLoginParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSdkPhoneLoginRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SdkPhoneLogin(ctx context.Context, params *SdkPhoneLoginParams, body SdkPhoneLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSdkPhoneLoginRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SdkPhoneSendCodeWithBody(ctx context.Context, params *SdkPhoneSendCodeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSdkPhoneSendCodeRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SdkPhoneSendCode(ctx context.Context, params *SdkPhoneSendCodeParams, body SdkPhoneSendCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSdkPhoneSendCodeRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SdkMerchantVerifyTokenWithBody(ctx context.Context, params *SdkMerchantVerifyTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSdkMerchantVerifyTokenRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SdkMerchantVerifyToken(ctx context.Context, params *SdkMerchantVerifyTokenParams, body SdkMerchantVerifyTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSdkMerchantVerifyTokenRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSdkPhoneLoginRequest calls the generic SdkPhoneLogin builder with application/json body
func NewSdkPhoneLoginRequest(server string, params *SdkPhoneLoginParams, body SdkPhoneLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSdkPhoneLoginRequestWithBody(server, params, "application/json", bodyReader)
}

// NewSdkPhoneLoginRequestWithBody generates requests for SdkPhoneLogin with any type of body
func NewSdkPhoneLoginRequestWithBody(server string, params *SdkPhoneLoginParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sdk/v1/auth/phone/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-App-ID", runtime.ParamLocationHeader, params.XAppID)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-App-ID", headerParam0)

	}

	return req, nil
}

// NewSdkPhoneSendCodeRequest calls the generic SdkPhoneSendCode builder with application/json body
func NewSdkPhoneSendCodeRequest(server string, params *SdkPhoneSendCodeParams, body SdkPhoneSendCodeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSdkPhoneSendCodeRequestWithBody(server, params, "application/json", bodyReader)
}

// NewSdkPhoneSendCodeRequestWithBody generates requests for SdkPhoneSendCode with any type of body
func NewSdkPhoneSendCodeRequestWithBody(server string, params *SdkPhoneSendCodeParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sdk/v1/auth/phone/send-code")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-App-ID", runtime.ParamLocationHeader, params.XAppID)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-App-ID", headerParam0)

	}

	return req, nil
}

// NewSdkMerchantVerifyTokenRequest calls the generic SdkMerchantVerifyToken builder with application/json body
func NewSdkMerchantVerifyTokenRequest(server string, params *SdkMerchantVerifyTokenParams, body SdkMerchantVerifyTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSdkMerchantVerifyTokenRequestWithBody(server, params, "application/json", bodyReader)
}

// NewSdkMerchantVerifyTokenRequestWithBody generates requests for SdkMerchantVerifyToken with any type of body
func NewSdkMerchantVerifyTokenRequestWithBody(server string, params *SdkMerchantVerifyTokenParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sdk/v1/merchant/verify-token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Timestamp", runtime.ParamLocationHeader, params.XTimestamp)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Timestamp", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Nonce", runtime.ParamLocationHeader, params.XNonce)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Nonce", headerParam1)

		var headerParam2 string

		headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-Signature", runtime.ParamLocationHeader, params.XSignature)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Signature", headerParam2)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SdkPhoneLoginWithBodyWithResponse request with any body
	SdkPhoneLoginWithBodyWithResponse(ctx context.Context, params *SdkPhoneLoginParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SdkPhoneLoginResponse, error)

	SdkPhoneLoginWithResponse(ctx context.Context, params *SdkPhoneLoginParams, body SdkPhoneLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*SdkPhoneLoginResponse, error)

	// SdkPhoneSendCodeWithBodyWithResponse request with any body
	SdkPhoneSendCodeWithBodyWithResponse(ctx context.Context, params *SdkPhoneSendCodeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SdkPhoneSendCodeResponse, error)

	SdkPhoneSendCodeWithResponse(ctx context.Context, params *SdkPhoneSendCodeParams, body SdkPhoneSendCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*SdkPhoneSendCodeResponse, error)

	// SdkMerchantVerifyTokenWithBodyWithResponse request with any body
	SdkMerchantVerifyTokenWithBodyWithResponse(ctx context.Context, params *SdkMerchantVerifyTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SdkMerchantVerifyTokenResponse, error)

	SdkMerchantVerifyTokenWithResponse(ctx context.Context, params *SdkMerchantVerifyTokenParams, body SdkMerchantVerifyTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*SdkMerchantVerifyTokenResponse, error)
}

type SdkPhoneLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
	JSON400 *BadRequest
	JSON401 *Unauthorized
	JSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r SdkPhoneLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SdkPhoneLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SdkPhoneSendCodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// ExpiresIn Code validity in seconds
		ExpiresIn *int    `json:"expires_in,omitempty"`
		Message   *string `json:"message,omitempty"`
		Success   *bool   `json:"success,omitempty"`
	}
	JSON400 *BadRequest
	JSON429 *ErrorResponse
	JSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r SdkPhoneSendCodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SdkPhoneSendCodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SdkMerchantVerifyTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MerchantVerifyTokenResponse
	JSON400      *BadRequest
	JSON401      *ErrorResponse
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r SdkMerchantVerifyTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SdkMerchantVerifyTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SdkPhoneLoginWithBodyWithResponse request with arbitrary body returning *SdkPhoneLoginResponse
func (c *ClientWithResponses) SdkPhoneLoginWithBodyWithResponse(ctx context.Context, params *SdkPhoneLoginParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SdkPhoneLoginResponse, error) {
	rsp, err := c.SdkPhoneLoginWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSdkPhoneLoginResponse(rsp)
}

func (c *ClientWithResponses) SdkPhoneLoginWithResponse(ctx context.Context, params *SdkPhoneLoginParams, body SdkPhoneLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*SdkPhoneLoginResponse, error) {
	rsp, err := c.SdkPhoneLogin(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSdkPhoneLoginResponse(rsp)
}

// SdkPhoneSendCodeWithBodyWithResponse request with arbitrary body returning *SdkPhoneSendCodeResponse
func (c *ClientWithResponses) SdkPhoneSendCodeWithBodyWithResponse(ctx context.Context, params *SdkPhoneSendCodeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SdkPhoneSendCodeResponse, error) {
	rsp, err := c.SdkPhoneSendCodeWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSdkPhoneSendCodeResponse(rsp)
}

func (c *ClientWithResponses) SdkPhoneSendCodeWithResponse(ctx context.Context, params *SdkPhoneSendCodeParams, body SdkPhoneSendCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*SdkPhoneSendCodeResponse, error) {
	rsp, err := c.SdkPhoneSendCode(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSdkPhoneSendCodeResponse(rsp)
}

// SdkMerchantVerifyTokenWithBodyWithResponse request with arbitrary body returning *SdkMerchantVerifyTokenResponse
func (c *ClientWithResponses) SdkMerchantVerifyTokenWithBodyWithResponse(ctx context.Context, params *SdkMerchantVerifyTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SdkMerchantVerifyTokenResponse, error) {
	rsp, err := c.SdkMerchantVerifyTokenWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSdkMerchantVerifyTokenResponse(rsp)
}

func (c *ClientWithResponses) SdkMerchantVerifyTokenWithResponse(ctx context.Context, params *SdkMerchantVerifyTokenParams, body SdkMerchantVerifyTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*SdkMerchantVerifyTokenResponse, error) {
	rsp, err := c.SdkMerchantVerifyToken(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSdkMerchantVerifyTokenResponse(rsp)
}

// ParseSdkPhoneLoginResponse parses an HTTP response from a SdkPhoneLoginWithResponse call
func ParseSdkPhoneLoginResponse(rsp *http.Response) (*SdkPhoneLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SdkPhoneLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseSdkPhoneSendCodeResponse parses an HTTP response from a SdkPhoneSendCodeWithResponse call
func ParseSdkPhoneSendCodeResponse(rsp *http.Response) (*SdkPhoneSendCodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SdkPhoneSendCodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// ExpiresIn Code validity in seconds
			ExpiresIn *int    `json:"expires_in,omitempty"`
			Message   *string `json:"message,omitempty"`
			Success   *bool   `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseSdkMerchantVerifyTokenResponse parses an HTTP response from a SdkMerchantVerifyTokenWithResponse call
func ParseSdkMerchantVerifyTokenResponse(rsp *http.Response) (*SdkMerchantVerifyTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SdkMerchantVerifyTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MerchantVerifyTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
