// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    *string `json:"code,omitempty"`
	Error   *string `json:"error,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// MerchantVerifyTokenRequest defines model for MerchantVerifyTokenRequest.
type MerchantVerifyTokenRequest struct {
	// MerchantId Merchant ID for signature verification
	MerchantId string `json:"merchant_id"`

	// Token JWT access token to verify
	Token string `json:"token"`
}

// MerchantVerifyTokenResponse defines model for MerchantVerifyTokenResponse.
type MerchantVerifyTokenResponse struct {
	Data *struct {
		// Email User email (if available)
		Email *openapi_types.Email `json:"email,omitempty"`

		// MerchantId Merchant ID from token
		MerchantId *string `json:"merchant_id,omitempty"`

		// Phone User phone (if available)
		Phone *string `json:"phone,omitempty"`

		// Status Account status
		Status *string `json:"status,omitempty"`

		// UserId User ID
		UserId *string `json:"user_id,omitempty"`

		// Username Username
		Username *string `json:"username,omitempty"`
	} `json:"data,omitempty"`
	Success *bool `json:"success,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// SdkMerchantVerifyTokenParams defines parameters for SdkMerchantVerifyToken.
type SdkMerchantVerifyTokenParams struct {
	// XTimestamp Unix timestamp in seconds
	XTimestamp string `json:"X-Timestamp"`

	// XNonce Random nonce string for replay protection
	XNonce string `json:"X-Nonce"`

	// XSignature Request signature generated using app_secret
	XSignature string `json:"X-Signature"`
}

// SdkMerchantVerifyTokenJSONRequestBody defines body for SdkMerchantVerifyToken for application/json ContentType.
type SdkMerchantVerifyTokenJSONRequestBody = MerchantVerifyTokenRequest
